In [1]:
import os
import glob
import pandas as pd
import numpy as np
import math

def train_val_test_split(lst_data:list):
    idx1 = int(round(len(lst_data)*0.8,0))
    train = lst_data[:idx1]
    sub = lst_data[idx1:]
    idx2 = int(round(len(sub)*0.5,0))
    val = sub[:idx2]
    test = sub[idx2:]
    return train,val,test


In [12]:
# def train_val_test_split(lst_data:list):
#     idx1 = int(round(len(lst_data)*0.8,0))
#     train = lst_data[:idx1]
#     val = lst_data[idx1:]
#     return train,val

In [13]:
# lst_img_lzd = glob.glob("D:/hh/dataset02/*")
# train_img_lzd,val_img_lzd = train_val_test_split(lst_img_lzd)
# lst_labels_lzd = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/yolov5/runs/detect/exp4/labels/*")
# train_labels_lzd,val_lables_lzd= train_val_test_split(lst_labels_lzd)
# lst_img_mango = glob.glob("D:/hh/dataset03/*")
# train_img_mango,val_img_mango = train_val_test_split(lst_img_mango)
# lst_labels_mango = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/yolov5/runs/detect/exp7/labels/*")
# train_labels_mango,val_lables_mango = train_val_test_split(lst_labels_mango)
# lst_img_sp = glob.glob("D:/hh/dataset01/IMAGES/*")
# train_img_sp,val_img_sp = train_val_test_split(lst_img_sp)
# lst_labels_sp = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/yolov5/runs/detect/exp3/labels/*")
# train_labels_sp,val_lables_sp = train_val_test_split(lst_labels_sp)

In [15]:
# train_img = train_img_lzd + train_img_mango + train_img_sp
# print(len(train_img))
# train_labels = train_labels_lzd + train_labels_mango + train_labels_sp
# print(len(train_labels))
# val_img = val_img_lzd + val_img_mango + val_img_sp
# print(len(val_img))
# val_labels = val_lables_lzd + val_lables_mango + val_lables_sp
# print(len(val_labels))

2342
2342
586
586


In [19]:
# copy_file(val_img,'D:/hh/detect/dataset/ecommerce/images/val')

In [2]:
lst_img_lzd = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/lazada_crawler/result/*")
train_img_lzd,val_img_lzd,test_img_lzd = train_val_test_split(lst_img_lzd)
lst_labels_lzd = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/lazada_crawler/labels/*")
train_labels_lzd,val_lables_lzd,test_labels_lzd = train_val_test_split(lst_labels_lzd)
lst_img_mango = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/Mango_crawler/result/*")
train_img_mango,val_img_mango,test_img_mango = train_val_test_split(lst_img_mango)
lst_labels_mango = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/Mango_crawler/labels/*")
train_labels_mango,val_lables_mango,test_labels_mango = train_val_test_split(lst_labels_mango)
lst_img_sp = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/shopee_crawler/result/*")
train_img_sp,val_img_sp,test_img_sp = train_val_test_split(lst_img_sp)
lst_labels_sp = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/shopee_crawler/labels/*")
train_labels_sp,val_lables_sp,test_labels_sp = train_val_test_split(lst_labels_sp)


In [3]:
train_img = train_img_lzd + train_img_mango + train_img_sp
print(len(train_img))
train_labels = train_labels_lzd + train_labels_mango + train_labels_sp
print(len(train_labels))
val_img = val_img_lzd + val_img_mango + val_img_sp
print(len(val_img))
val_labels = val_lables_lzd + val_lables_mango + val_lables_sp
print(len(val_labels))
test_img = test_img_lzd + test_img_mango + test_img_sp
print(len(test_img))
test_labels = test_labels_lzd + test_labels_mango + test_labels_sp
print(len(test_labels))

9300
9300
1162
1162
1163
1163


In [4]:
import glob
import os
import shutil
# Grabs all the files that have extension (jpg)
def copy_file(lst_path_copyfile,des_dir):
    for f in lst_path_copyfile:
        shutil.copy(f, des_dir)
    return None

In [11]:
copy_file(test_img,'D:/hh/detect/dataset/ecommerce/images/test')

In [3]:
from ultralytics import YOLO
 
# Load the model.
model = YOLO('yolov8n.pt')
 
# Training.
results = model.train(
   data='D:/hh/ultralytics/ultralytics/cfg/datasets/ecommerce.yaml',
   imgsz=640,
   epochs=10,
   batch=8,
   name='yolov8n_custom'
)

New https://pypi.org/project/ultralytics/8.0.141 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.123  Python-3.9.13 torch-2.0.1+cpu CPU
yolo\engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=D:/hh/ultralytics/ultralytics/cfg/datasets/ecommerce.yaml, epochs=10, patience=50, batch=8, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=yolov8n_custom, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, c

In [4]:
from ultralytics import YOLO
 
# Load the model.
# model = YOLO('yolov8n.pt')
model = YOLO('D:/hh/ultralytics/ultralytics/runs/detect/yolov8n_custom/weights/best.pt')
 
# Training.
results = model.val(
   data='D:/hh/ultralytics/ultralytics/cfg/datasets/ecommerce.yaml',
   imgsz=640,
   batch=1
)

Ultralytics YOLOv8.0.123  Python-3.9.13 torch-2.0.1+cpu CPU
Model summary (fused): 168 layers, 3007598 parameters, 0 gradients
val: Scanning D:\hh\ultralytics\ultralytics\dataset\ecommerce\labels\val10.cache... 3 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3/3 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 3/3 [00:01<00:00,  2.01it/s]
                   all          3          8     0.0157       0.75      0.313      0.217
                 shirt          3          2     0.0217          1      0.221     0.0558
                 pants          3          2     0.0115          1     0.0362     0.0148
                   bag          3          1     0.0294          1      0.995      0.796
                  shoe          3          3          0          0          0          0
Speed: 5.0ms preprocess, 334.1ms inference, 0.0ms loss, 25.6ms postprocess per image
Results saved to runs\detect\val


In [6]:
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
# model = YOLO('yolov8n.pt')
model = YOLO('D:/hh/ultralytics/ultralytics/runs/detect/yolov8n_custom/weights/last.pt')

# Run inference on 'bus.jpg' with arguments
model.predict('D:/hh/detect/video/00a6187c83dba449b9f0ba3a2649bb43.jpg', save_crop=True, imgsz=640, conf=0.1)


image 1/1 D:\hh\detect\video\00a6187c83dba449b9f0ba3a2649bb43.jpg: 640x640 (no detections), 434.9ms
Speed: 44.9ms preprocess, 434.9ms inference, 11.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict2


[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes']
 masks: None
 names: {0: 'sunglass', 1: 'hat', 2: 'jacket', 3: 'shirt', 4: 'pants', 5: 'shorts', 6: 'skirt', 7: 'dress', 8: 'bag', 9: 'shoe'}
 orig_img: array([[[ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241],
         ...,
         [ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241]],
 
        [[ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241],
         ...,
         [ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241]],
 
        [[ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241],
         ...,
         [ 38,  91, 241],
         [ 38,  91, 241],
         [ 38,  91, 241]],
 
        ...,
 
        [[ 49, 159, 249],
         [ 49, 159, 249],
         [ 49, 159, 249],
         ...,
         [ 49, 159, 249],
         [ 49, 159, 249],
         [ 49, 1

In [1]:
from ultralytics import YOLO
from torchsummary import summary
import torch
import torch.nn as nn
class Identity(nn.Module):
    def __init__(self):
        super(Identity, self).__init__()
        
    def forward(self, x):
        return x
model = torch.load('D:/hh/ultralytics/ultralytics/runs/detect/yolov8n_custom/weights/best.pt', map_location=torch.device('cpu'))['model']
print(model)
# modelA = model.model[:22]
# torch.save(modelA, 'D:/hh/ultralytics/ultralytics/runs/detect/test.pt')

DetectionModel(
  (model): Sequential(
    (0): Conv(
      (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (1): Conv(
      (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (2): C2f(
      (cv1): Conv(
        (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(48, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    

In [43]:
list(model.parameters())[0].shape

torch.Size([16, 3, 3, 3])

In [76]:
import cv2
import numpy as np
from torchvision.transforms import transforms
img = cv2.imread('D:/hh/ultralytics/ultralytics/dataset/ecommerce/images/train10/00a6187c83dba449b9f0ba3a2649bb43.jpg')
print(img.shape)
transform = transforms.ToTensor()
inputs = transform(img)
print(inputs.shape)
inputs = torch.unsqueeze(inputs,0)
print(inputs.shape)

(1024, 1024, 3)
torch.Size([3, 1024, 1024])
torch.Size([1, 3, 1024, 1024])


In [107]:
from ultralytics import YOLO
from torchsummary import summary
from ultralytics.nn.tasks import *
model = YOLO('yolov8n.pt')
pred = BaseModel._predict_once(model.model,inputs)
print(pred)



(tensor([[[3.1678e+00, 1.8853e+01, 2.3114e+01,  ..., 8.6280e+02, 8.9173e+02, 9.5911e+02],
         [3.3953e+00, 2.7087e+00, 2.6812e+00,  ..., 9.9787e+02, 9.9627e+02, 9.9592e+02],
         [6.3055e+00, 3.7112e+01, 4.5677e+01,  ..., 3.2824e+02, 2.6948e+02, 1.4122e+02],
         ...,
         [1.1355e-07, 8.9197e-08, 8.5102e-08,  ..., 8.8285e-07, 8.7752e-07, 1.1942e-06],
         [7.8631e-08, 7.6477e-08, 6.0000e-08,  ..., 1.2715e-06, 1.2974e-06, 1.3052e-06],
         [2.3903e-07, 1.1269e-07, 9.6087e-08,  ..., 1.4856e-06, 1.5743e-06, 1.6412e-06]]]), [tensor([[[[  8.1318,   3.8700,   1.9592,  ...,   0.5442,   1.7044,   4.3655],
          [  8.0993,   3.3917,   2.0497,  ...,  -0.1122,   2.9216,   8.0914],
          [  8.2286,   3.9548,   1.9552,  ...,   0.0444,   3.0804,   7.8880],
          ...,
          [  8.2885,   4.5804,   1.9463,  ...,   1.8726,   4.9647,   7.9993],
          [  7.9340,   4.1173,   2.1607,  ...,   0.8746,   3.5792,   8.3293],
          [  7.5233,   4.0502,   2.3055,  

In [112]:
# pred = torch.as_tensor(pred[0])
out = pred[0].detach().numpy()
print(out)

[[[     3.1678      18.853      23.114 ...       862.8      891.73      959.11]
  [     3.3953      2.7087      2.6812 ...      997.87      996.27      995.92]
  [     6.3055      37.112      45.677 ...      328.24      269.48      141.22]
  ...
  [ 1.1355e-07  8.9197e-08  8.5102e-08 ...  8.8285e-07  8.7752e-07  1.1942e-06]
  [ 7.8631e-08  7.6477e-08       6e-08 ...  1.2715e-06  1.2974e-06  1.3052e-06]
  [ 2.3903e-07  1.1269e-07  9.6087e-08 ...  1.4856e-06  1.5743e-06  1.6412e-06]]]


In [ ]:
from ultralytics import YOLO

# Load a model
model = YOLO('D:/hh/detect/src/runs/detect/yolov8n_custom/weights/test.pt')  # load a partially trained model,copy best weight.pt to test.pt

# Resume training
model.train(resume=True)

In [18]:
import json
import pandas as pd
import re
with open('D:/hh/detect/json/insta.json', 'r') as f:
    data = json.load(f)
temp = pd.DataFrame(data['post_meta'])
df = temp[['mediaid','insta_url','links']].iloc[1:,:]
df = df.explode('links')
df['parse_name'] = df['links'].apply(lambda x: re.findall("//.*/(.*)\?", x))
df['img_name'] = df['parse_name'].apply(lambda x: ''.join(x))
df


mediaid                             insta_url  \
1     2854765639637532206  https://instagram.com/p/CeeKjlblf4u/   
2     3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
2     3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
2     3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
2     3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
...                   ...                                   ...   
3136  2912861947911510492  https://instagram.com/p/ChskII1BJnc/   
3136  2912861947911510492  https://instagram.com/p/ChskII1BJnc/   
3137  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   
3137  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   
3137  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   

                                                  links  \
1     https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
2     https://instagram.fsgn13-4.fna.fbcdn.net/v/t51...   
2     https://instagram.fsgn4-1.fna.fbcdn.net/v/t51....   
2     https://instagram.fsgn13-3.fna.fbcdn.net/v/t51...   
2     https://instagram.fsgn8-3.fna.fbcdn.net/v/t51....   
...                                                 ...   
3136  https://instagram.fsgn8-4.fna.fbcdn.net/v/t51....   
3136  https://instagram.fsgn8-4.fna.fbcdn.net/v/t51....   
3137  https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
3137  https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
3137  https://instagram.fsgn13-4.fna.fbcdn.net/v/t51...   

                                             parse_name  \
1     [286427905_782090846505647_3529461111420111113...   
2     [352659062_280002557822263_4357588945128279421...   
2     [352769598_2927874854012259_509585787132942420...   
2     [353438856_217043704593410_8787117839196339590...   
2     [353421901_1685279631925092_854834867909798800...   
...                                                 ...   
3136  [301170709_5598714330151760_222849326006710059...   
3136  [301393447_607025857758932_9140184030591590578...   
3137  [291818337_604007951442275_6336174475050824249...   
3137  [291681100_1007102999998108_886258372973445007...   
3137  [291634199_143703311597851_1894033055454994632...   

                                               img_name  
1     286427905_782090846505647_3529461111420111113_...  
2     352659062_280002557822263_4357588945128279421_...  
2     352769598_2927874854012259_509585787132942420_...  
2     353438856_217043704593410_8787117839196339590_...  
2     353421901_1685279631925092_8548348679097988000...  
...                                                 ...  
3136  301170709_5598714330151760_2228493260067100591...  
3136  301393447_607025857758932_9140184030591590578_...  
3137  291818337_604007951442275_6336174475050824249_...  
3137  291681100_1007102999998108_8862583729734450074...  
3137  291634199_143703311597851_1894033055454994632_...  

[10551 rows x 5 columns]

In [20]:
import cv2
from torchvision.transforms import transforms
import torch



class Transform:
   def __init__(self):
      super(Transform,self).__init__()
      # self.tf = transforms.ToTensor()
      self.tf = transforms.Compose([
        transforms.Resize((640,640)),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], 
                             std=[0.229, 0.224, 0.225])
        ])
      
   def transform(self,img):
      inputs = self.tf(img)
      input = torch.unsqueeze(inputs,0)
      return input
   

In [32]:
from ultralytics import YOLO
from torchsummary import summary
from ultralytics.nn.tasks import *
import glob
from PIL import Image

lst_img = glob.glob('D:/hh/ultralytics/ultralytics/dataset/ecommerce/images/train10/*')
t = Transform()

lst_img_name = []
lst_encode_img = []
for image in lst_img:
    p = image.split("\\")[-1]
    print(p)
    lst_img_name.append(p)
    model = YOLO('yolov8n.pt')
    img = Image.open(image)
    input = t.transform(img)
    pred = BaseModel._predict_once(model.model,input)
    out = pred[0].detach().numpy()
    print(out)
    lst_encode_img.append(out)


280693238_780185813350864_4674360865255087100_n.jpg
[[[     6.1949      21.683      26.969 ...      479.69      495.17      517.11]
  [     4.6314      5.2475      3.4956 ...      607.53      605.89      610.53]
  [     12.187      42.572      49.851 ...      318.34      286.95      246.34]
  ...
  [ 4.4065e-07  2.9653e-07  2.5383e-07 ...   4.614e-07  3.8491e-07  3.4599e-07]
  [ 3.6199e-07  3.4857e-07  2.5299e-07 ...  7.0964e-07   6.505e-07  6.5858e-07]
  [ 6.8645e-07   3.258e-07  1.8399e-07 ...  6.0548e-07   5.292e-07  5.5616e-07]]]
284562775_108591785143890_4691473088196714546_n.jpg
[[[     3.3834      22.347      29.745 ...      393.75      422.94      465.07]
  [     3.3401      2.6423      2.5651 ...      593.01      591.98      591.07]
  [     6.8016      43.673      58.582 ...      416.43      432.61      349.95]
  ...
  [ 1.1653e-07  8.4547e-08  9.6978e-08 ...  5.3507e-08  6.4103e-07   9.573e-06]
  [ 1.1444e-07  1.0667e-07   1.008e-07 ...  5.9302e-07  6.7306e-07  2.2088e-06]
  

In [33]:
extract_feature = pd.DataFrame(columns = ['img_name','vector'])
extract_feature['img_name'] = lst_img_name
extract_feature['vector'] = lst_encode_img
extract_feature

img_name  \
0  280693238_780185813350864_4674360865255087100_...   
1  284562775_108591785143890_4691473088196714546_...   
2  284762815_400824831946338_7545515423930285111_...   
3  284804270_511933474008759_5795111452857605378_...   
4  284945370_1074020276877450_2099414914543869429...   
5  285006373_5007962649322268_8303843748788485142...   
6  285071253_751538772550095_9179891121634772317_...   
7  285072252_3176017756006116_5455743096972587895...   

                                              vector  
0  [[[6.194855, 21.682976, 26.96894, 30.201061, 3...  
1  [[[3.3834004, 22.347359, 29.74498, 37.829723, ...  
2  [[[13.222295, 17.20216, 27.635891, 27.9962, 29...  
3  [[[3.2259355, 19.672512, 22.785599, 30.112482,...  
4  [[[23.379175, 30.872162, 41.7781, 48.220455, 5...  
5  [[[26.816782, 23.993887, 21.997383, 27.889488,...  
6  [[[7.0285153, 18.74022, 21.588697, 29.5385, 42...  
7  [[[20.398085, 24.866602, 25.583605, 29.668732,...

In [36]:
h = pd.merge(df, extract_feature, on='img_name', how='left')
h

mediaid                             insta_url  \
0      2854765639637532206  https://instagram.com/p/CeeKjlblf4u/   
1      3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
2      3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
3      3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
4      3122847265304859583  https://instagram.com/p/CtWlQrQS9O_/   
...                    ...                                   ...   
10546  2912861947911510492  https://instagram.com/p/ChskII1BJnc/   
10547  2912861947911510492  https://instagram.com/p/ChskII1BJnc/   
10548  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   
10549  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   
10550  2874838601469747537  https://instagram.com/p/Cflenn7L2FR/   

                                                   links  \
0      https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
1      https://instagram.fsgn13-4.fna.fbcdn.net/v/t51...   
2      https://instagram.fsgn4-1.fna.fbcdn.net/v/t51....   
3      https://instagram.fsgn13-3.fna.fbcdn.net/v/t51...   
4      https://instagram.fsgn8-3.fna.fbcdn.net/v/t51....   
...                                                  ...   
10546  https://instagram.fsgn8-4.fna.fbcdn.net/v/t51....   
10547  https://instagram.fsgn8-4.fna.fbcdn.net/v/t51....   
10548  https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
10549  https://instagram.fsgn3-1.fna.fbcdn.net/v/t51....   
10550  https://instagram.fsgn13-4.fna.fbcdn.net/v/t51...   

                                              parse_name  \
0      [286427905_782090846505647_3529461111420111113...   
1      [352659062_280002557822263_4357588945128279421...   
2      [352769598_2927874854012259_509585787132942420...   
3      [353438856_217043704593410_8787117839196339590...   
4      [353421901_1685279631925092_854834867909798800...   
...                                                  ...   
10546  [301170709_5598714330151760_222849326006710059...   
10547  [301393447_607025857758932_9140184030591590578...   
10548  [291818337_604007951442275_6336174475050824249...   
10549  [291681100_1007102999998108_886258372973445007...   
10550  [291634199_143703311597851_1894033055454994632...   

                                                img_name vector  
0      286427905_782090846505647_3529461111420111113_...    NaN  
1      352659062_280002557822263_4357588945128279421_...    NaN  
2      352769598_2927874854012259_509585787132942420_...    NaN  
3      353438856_217043704593410_8787117839196339590_...    NaN  
4      353421901_1685279631925092_8548348679097988000...    NaN  
...                                                  ...    ...  
10546  301170709_5598714330151760_2228493260067100591...    NaN  
10547  301393447_607025857758932_9140184030591590578_...    NaN  
10548  291818337_604007951442275_6336174475050824249_...    NaN  
10549  291681100_1007102999998108_8862583729734450074...    NaN  
10550  291634199_143703311597851_1894033055454994632_...    NaN  

[10551 rows x 6 columns]

In [54]:
import json
import pandas as pd
import re
with open('D:/hh/detect/json/tiktok.json', 'r',encoding='utf8') as f:
    data = json.load(f)
temp = pd.DataFrame(data['video_meta'])
df_tiktok = temp[['account','meta_post']].iloc[1:,:]
df_tiktok['post'] = df_tiktok['meta_post'].apply(lambda x: x.keys())
df_tiktok = df_tiktok.explode('post')
df_tiktok['img_name'] = df_tiktok['post'].apply(lambda x: x.split("/")[-1])
df_tiktok

account  \
1   https://www.tiktok.com/@hoaa.hanassii?lang=en   
1   https://www.tiktok.com/@hoaa.hanassii?lang=en   
1   https://www.tiktok.com/@hoaa.hanassii?lang=en   
1   https://www.tiktok.com/@hoaa.hanassii?lang=en   
1   https://www.tiktok.com/@hoaa.hanassii?lang=en   
..                                            ...   
34          https://www.tiktok.com/@ttb88?lang=en   
34          https://www.tiktok.com/@ttb88?lang=en   
34          https://www.tiktok.com/@ttb88?lang=en   
34          https://www.tiktok.com/@ttb88?lang=en   
34          https://www.tiktok.com/@ttb88?lang=en   

                                            meta_post  \
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
..                                                ...   
34  {'https://www.tiktok.com/@ttb88/video/72529553...   
34  {'https://www.tiktok.com/@ttb88/video/72529553...   
34  {'https://www.tiktok.com/@ttb88/video/72529553...   
34  {'https://www.tiktok.com/@ttb88/video/72529553...   
34  {'https://www.tiktok.com/@ttb88/video/72529553...   

                                                 post             img_name  
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7251930662595218693  
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7250449828205825285  
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7248972668026866950  
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7248214089997110533  
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7247861865718598918  
..                                                ...                  ...  
34  https://www.tiktok.com/@ttb88/video/7219559484...  7219559484274920730  
34  https://www.tiktok.com/@ttb88/video/7219249528...  7219249528166288667  
34  https://www.tiktok.com/@ttb88/video/7218163818...  7218163818541763866  
34  https://www.tiktok.com/@ttb88/video/7215116970...  7215116970612608283  
34  https://www.tiktok.com/@ttb88/video/7214470102...  7214470102329101594  

[1152 rows x 4 columns]

In [61]:
from ultralytics import YOLO
from torchsummary import summary
from ultralytics.nn.tasks import *
import glob
from PIL import Image

lst_vid = glob.glob('D:/hh/detect/video/*.jpg')
t = Transform()

lst_img_name = []
lst_encode_img = []
for image in lst_vid:
    p = image.split("\\")[-1].split(".")[0]
    print(p)
    lst_img_name.append(p)
    model = YOLO('yolov8n.pt')
    img = Image.open(image)
    input = t.transform(img)
    pred = BaseModel._predict_once(model.model,input)
    out = pred[0].detach().numpy()
    print(out)
    lst_encode_img.append(out)


7220024739106966811
[[[     3.5887      23.773      28.357 ...      490.21       578.8      581.49]
  [       3.63      2.7235      2.6666 ...       587.2      585.35      589.04]
  [     6.9943      46.747      55.323 ...      298.36      120.03      116.44]
  ...
  [ 1.0164e-07   1.105e-07  1.2867e-07 ...  2.3713e-06  6.8077e-06  2.6086e-05]
  [ 1.1147e-07  1.5189e-07  1.4084e-07 ...  1.7929e-06  3.4841e-06  5.0661e-06]
  [ 2.4559e-07  1.5671e-07   1.137e-07 ...  2.2238e-06  3.6513e-06  5.5301e-06]]]
7220024739106966811
[[[     3.4542      24.249      28.725 ...      504.48      516.16      529.54]
  [     3.6024      2.6805      2.6552 ...      603.81      602.31      582.74]
  [     6.7227      47.729      56.126 ...      270.26      246.39      220.87]
  ...
  [ 1.0187e-07  1.0713e-07  1.3037e-07 ...  1.6891e-06  2.0452e-06  1.1659e-06]
  [ 9.6504e-08  1.1847e-07  1.0959e-07 ...  3.8891e-06   2.531e-06  1.4573e-06]
  [ 2.1132e-07  1.2087e-07  9.1325e-08 ...   8.054e-06  4.0576e-06

In [62]:
extract_feature_2 = pd.DataFrame(columns = ['img_name','vector'])
extract_feature_2['img_name'] = lst_img_name
extract_feature_2['vector'] = lst_encode_img
extract_feature_2

img_name                                             vector
0   7220024739106966811  [[[3.5886598, 23.77333, 28.356743, 33.87114, 4...
1   7220024739106966811  [[[3.454248, 24.249222, 28.724874, 33.99211, 4...
2   7220024739106966811  [[[3.4093583, 22.952053, 26.766464, 31.846207,...
3   7220024739106966811  [[[3.4619522, 24.067024, 28.048233, 33.87057, ...
4   7220024739106966811  [[[3.5321174, 24.18377, 27.957794, 32.792473, ...
5   7220024739106966811  [[[3.460986, 25.172241, 29.99855, 36.35889, 43...
6   7220024739106966811  [[[3.4728765, 24.277977, 28.311436, 33.8302, 4...
7   7227758297196023045  [[[6.787271, 18.850372, 24.838406, 32.57939, 4...
8   7227758297196023045  [[[3.727891, 19.150024, 24.75914, 35.603806, 4...
9   7227758297196023045  [[[3.5787883, 19.453262, 26.128048, 36.99774, ...
10  7227758297196023045  [[[3.618247, 20.725994, 26.76062, 35.38981, 42...
11  7227758297196023045  [[[3.8528342, 19.280888, 23.56253, 33.201736, ...
12  7227758297196023045  [[[3.9246156, 22.430557, 29.702976, 34.738647,...
13  7227758297196023045  [[[3.80074, 21.003168, 28.434198, 37.5372, 47....
14  7227758297196023045  [[[4.4365635, 23.272242, 26.894579, 33.249176,...
15  7227758297196023045  [[[3.6695228, 23.78466, 29.596607, 35.14604, 3...
16  7227758297196023045  [[[3.5831928, 20.243177, 24.921513, 33.29183, ...
17  7227758297196023045  [[[3.3458076, 18.287212, 23.943508, 31.422508,...
18  7227893269164936453  [[[3.5953422, 18.458782, 24.674171, 30.627752,...
19  7227893269164936453  [[[3.1088064, 15.884008, 26.688673, 36.29971, ...
20  7227893269164936453  [[[4.252556, 19.706415, 26.070415, 30.61459, 3...
21  7227893269164936453  [[[5.128163, 19.753239, 22.975025, 28.295624, ...
22  7227893269164936453  [[[4.1774797, 19.780052, 26.12271, 33.964066, ...
23  7227893269164936453  [[[3.830977, 21.671326, 24.421043, 28.031982, ...

In [63]:
g = pd.merge(df_tiktok, extract_feature_2, on='img_name', how='inner')
g

account  \
0       https://www.tiktok.com/@hoaa.hanassii?lang=en   
1       https://www.tiktok.com/@hoaa.hanassii?lang=en   
2       https://www.tiktok.com/@hoaa.hanassii?lang=en   
3       https://www.tiktok.com/@hoaa.hanassii?lang=en   
4       https://www.tiktok.com/@hoaa.hanassii?lang=en   
5       https://www.tiktok.com/@hoaa.hanassii?lang=en   
6       https://www.tiktok.com/@hoaa.hanassii?lang=en   
7   https://www.tiktok.com/@truongdaitrang1555?lan...   
8   https://www.tiktok.com/@truongdaitrang1555?lan...   
9   https://www.tiktok.com/@truongdaitrang1555?lan...   
10  https://www.tiktok.com/@truongdaitrang1555?lan...   
11  https://www.tiktok.com/@truongdaitrang1555?lan...   
12  https://www.tiktok.com/@truongdaitrang1555?lan...   
13         https://www.tiktok.com/@linhbarbie?lang=en   
14         https://www.tiktok.com/@linhbarbie?lang=en   
15         https://www.tiktok.com/@linhbarbie?lang=en   
16         https://www.tiktok.com/@linhbarbie?lang=en   
17         https://www.tiktok.com/@linhbarbie?lang=en   
18         https://www.tiktok.com/@linhbarbie?lang=en   
19         https://www.tiktok.com/@linhbarbie?lang=en   
20         https://www.tiktok.com/@linhbarbie?lang=en   
21         https://www.tiktok.com/@linhbarbie?lang=en   
22         https://www.tiktok.com/@linhbarbie?lang=en   
23         https://www.tiktok.com/@linhbarbie?lang=en   

                                            meta_post  \
0   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
1   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
2   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
3   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
4   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
5   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
6   {'https://www.tiktok.com/@hoaa.hanassii/video/...   
7   {'https://www.tiktok.com/@truongdaitrang1555/v...   
8   {'https://www.tiktok.com/@truongdaitrang1555/v...   
9   {'https://www.tiktok.com/@truongdaitrang1555/v...   
10  {'https://www.tiktok.com/@truongdaitrang1555/v...   
11  {'https://www.tiktok.com/@truongdaitrang1555/v...   
12  {'https://www.tiktok.com/@truongdaitrang1555/v...   
13  {'https://www.tiktok.com/@linhbarbie/video/725...   
14  {'https://www.tiktok.com/@linhbarbie/video/725...   
15  {'https://www.tiktok.com/@linhbarbie/video/725...   
16  {'https://www.tiktok.com/@linhbarbie/video/725...   
17  {'https://www.tiktok.com/@linhbarbie/video/725...   
18  {'https://www.tiktok.com/@linhbarbie/video/725...   
19  {'https://www.tiktok.com/@linhbarbie/video/725...   
20  {'https://www.tiktok.com/@linhbarbie/video/725...   
21  {'https://www.tiktok.com/@linhbarbie/video/725...   
22  {'https://www.tiktok.com/@linhbarbie/video/725...   
23  {'https://www.tiktok.com/@linhbarbie/video/725...   

                                                 post             img_name  \
0   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
1   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
2   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
3   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
4   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
5   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
6   https://www.tiktok.com/@hoaa.hanassii/video/72...  7220024739106966811   
7   https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
8   https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
9   https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
10  https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
11  https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
12  https://www.tiktok.com/@truongdaitrang1555/vid...  7227893269164936453   
13  https://www.tiktok.com/@linhbarbie/video/72277...  7227758297196023045   
14  https://www.tiktok.c

In [14]:
import json
jsonfile = 'D:/hh/detect/json'
jsonfile = jsonfile + '/post_meta.json'
with open('D:/hh/detect/json/post_meta.json', 'r',encoding='utf8') as f:
    data = json.load(f)
    f.close()

In [ ]:
import os
import glob
import pandas as pd
import numpy as np
import math
import shutil

def train_val_test_split(lst_data:list):
    train = lst_data[:1000]
    return train
lst_img = glob.glob("C:/Users/DELL/Desktop/Master_K31/Final_project/Code/yolov5/colorful_fashion_dataset_for_object_detection/JPEGImages/*")
train_img = train_val_test_split(lst_img)
def copy_file(lst_path_copyfile,des_dir):
    for f in lst_path_copyfile:
        shutil.copy(f, des_dir)
    return None
copy_file(train_img,'D:/hh/dataset03')


In [132]:
import torchvision.models as models
import torch
import time
import matplotlib.pyplot as plt
from torchvision import transforms
model = models.efficientnet_b0(pretrained=True)
model.eval()

c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=EfficientNet_B0_Weights.IMAGENET1K_V1`. You can also use `weights=EfficientNet_B0_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


EfficientNet(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): SiLU(inplace=True)
    )
    (1): Sequential(
      (0): MBConv(
        (block): Sequential(
          (0): Conv2dNormActivation(
            (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
            (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): SiLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
            (activation): SiLU(inplace=True)
            (scale_activation): Sigmoid()
          )
          (2): Conv2dNormActivat

In [133]:
from PIL import Image
from torchvision import transforms

tfms = transforms.Compose([transforms.Resize((224,224)), transforms.CenterCrop((224,224)), 
                           transforms.ToTensor(),
                           transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),])

In [144]:
import glob
lst = glob.glob('D:/hh/detect/animals/*')
lst_vector = []
for i in lst:
    im = Image.open(i).convert('RGB')
    img = tfms(im).unsqueeze(0)
    with torch.no_grad():
        out = model(img)
        out = out.detach().numpy()
        out = out.flatten()
        print('-----------')
        print(out.shape)
        lst_vector.append(out)
    im.close()
    
    

-----------
(1000,)
-----------
(1000,)
-----------
(1000,)


In [154]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
label = [0,1,0]
df = pd.DataFrame(columns = ['vectors','labels'])
df['vectors'] = lst_vector
df['labels'] = label
X_train, X_test, y_train, y_test = train_test_split(df['vectors'], df['labels'], test_size = 0.2, random_state = 0)
#input data 
x=np.array(X_train.tolist())
#output data
y=np.array(y_train.tolist())

In [155]:
from sklearn import svm
svc=svm.SVC(C = 1, kernel = 'rbf', probability=True)
svc.fit(x,y)

SVC(C=1, probability=True)

In [160]:
from sklearn.metrics import accuracy_score
xt=np.array(X_test.tolist())
#output data
yt=np.array(y_test.tolist())
y_pred=svc.predict(xt)
print(y_pred)
print('Model accuracy score with linear kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(yt, y_pred)))

[1]
Model accuracy score with linear kernel and C=100.0 : 0.0000


In [156]:
test =  Image.open('D:/hh/detect/animals/cat.jpg').convert('RGB')
a = tfms(test).unsqueeze(0)
with torch.no_grad():
    out1 = model(a)
    out1 = out1.detach().numpy()
    out1 = out1.flatten()
    out1 = out1.reshape(1, -1)
pred = svc.predict(out1)
print(pred)



[1]
